# Generated by Django 2.1.4 on 2019-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.URLField()),
                ('article_text', models.TextField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('verification_code', models.CharField(max_length=4)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
